import Head from 'next/head'
import Front from '../components/Front/Front'
import Section2 from '../components/Section2/Section2'
import Section3 from '../components/Section3/Section3'
import Footer from '../components/Footer/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main>
       <Front/>
       <Section2/>
       <Section3/>
       <Footer/>
     </main>
    </div>
  )
}
